export default {
  RECEIVE_POLLS_REQUEST: 'RECEIVE_POLLS_REQUEST',
  RECEIVE_POLLS_SUCCESS: 'RECEIVE_POLLS_SUCCESS',
  RECEIVE_POLLS_FAIL: 'RECEIVE_POLLS_FAIL',

  GET_POLL_REQUEST: 'GET_POLL_REQUEST',
  GET_POLL_SUCCESS: 'GET_POLL_SUCCESS',
  GET_POLL_FAIL: 'GET_POLL_FAIL',

  ADD_NEW_POLL_SUCCESS: 'ADD_NEW_POLL_SUCCESS',
  ADD_NEW_POLL_FAIL: 'ADD_NEW_POLL_FAIL',
}