export default {
  RECEIVE_ALL_POLLS_REQUEST: 'RECEIVE_ALL_POLLS_REQUEST',
  RECEIVE_ALL_POLLS_SUCCESS: 'RECEIVE_ALL_POLLS_SUCCESS',
  RECEIVE_ALL_POLLS_FAIL: 'RECEIVE_ALL_POLLS_FAIL',

  RECEIVE_POLLS_REQUEST: 'RECEIVE_POLLS_REQUEST',
  RECEIVE_POLLS_SUCCESS: 'RECEIVE_POLLS_SUCCESS',
  RECEIVE_POLLS_FAIL: 'RECEIVE_POLLS_FAIL',

  GET_POLL_REQUEST: 'GET_POLL_REQUEST',
  GET_POLL_SUCCESS: 'GET_POLL_SUCCESS',
  GET_POLL_FAIL: 'GET_POLL_FAIL',

  ADD_NEW_POLL_SUCCESS: 'ADD_NEW_POLL_SUCCESS',
  ADD_NEW_POLL_FAIL: 'ADD_NEW_POLL_FAIL',

  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  // UPDATE_USER: 'UPDATE_USER',
}