export default {
  LOAD_POLLS_REQUEST: 'LOAD_POLLS_REQUEST',
  LOAD_POLLS_SUCCESS: 'LOAD_POLLS_SUCCESS',
  LOAD_POLLS_FAIL: 'LOAD_POLLS_FAIL',
  
  LOAD_POLL_REQUEST: 'LOAD_POLL_REQUEST',
  LOAD_POLL_SUCCESS: 'LOAD_POLL_SUCCESS',
  LOAD_POLL_FAIL: 'LOAD_POLL_FAIL'
}